complexity_indicators = [
    "time complexity",
    "quantum key distribution",
    "stochastic gradient descent",
    "computational neuroscience",
    "turbo equalization",
    "node classification",
    "fully homomorphic encryption (FHE)",
    "boosting",
    "cross-entropy",
    "interpretable ml",
    "autonomous systems",
    "spectrum sensing",
    "language model",
    "state estimation",
    "functional encryption",
    "hidden Markov model",
    "speech recognition",
    "data warehousing",
    "slam",
    "phase shift",
    "image processing",
    "ELT process",
    "auto-scaling",
    "remote procedure call",
    "finite element analysis",
    "checkpointing",
    "cointegration",
    "model predictive control",
    "cognitive architecture",
    "agile development",
    "finite difference method",
    "Kalman filter",
    "doppler effect",
    "numerical analysis",
    "distributed ledger",
    "SQL injection",
    "emotion detection",
    "ant colony optimization",
    "linear programming",
    "supercomputing",
    "attention mechanism",
    "network congestion",
    "link prediction",
    "autoencoder",
    "API gateway",
    "named entity recognition",
    "GPT",
    "high-performance computing",
    "beidou",
    "gradient vector",
    "neuromorphic computing",
    "guard interval",
    "biomedical engineering",
    "exponential smoothing",
    "geohashing",
    "adam optimizer",
    "sarcasm detection",
    "smart contracts",
    "fog computing",
    "tensor decomposition",
    "BASE properties",
    "rsa algorithm",
    "modular arithmetic",
    "operating systems",
    "orchestration",
    "bcrypt",
    "cloud computing",
    "machine learning",
    "gradient descent",
    "defeasible reasoning",
    "byzantine fault tolerance",
    "computational biology",
    "cross-chain communication",
    "multi-head attention",
    "quantum information theory",
    "quantum sensing",
    "command query responsibility segregation",
    "artificial intelligence",
    "rasterization",
    "ETL process",
    "orthogonal",
    "network slicing",
    "guard band",
    "graph algorithms",
    "differential evolution",
    "visual effects",
    "dynamic programming",
    "digital signal processing",
    "quantum field theory",
    "evolutionary algorithms",
    "grover's algorithm",
    "computational genomics",
    "computer vision",
    "footprint",
    "beta distribution",
    "hard margin",
    "wavelet transform",
    "hash-based cryptography",
    "smart contract",
    "navigation",
    "multimodal learning",
    "algorithm",
    "frequency-division duplex",
    "natural language processing",
    "massive mimo",
    "augmented reality",
    "XGBoost",
    "ray tracing",
    "multi-armed bandit",
    "quantum internet",
    "multi-carrier",
    "qr decomposition",
    "greedy algorithm",
    "genome sequencing",
    "telepresence",
    "neural architecture search",
    "mechanism design",
    "load balancing",
    "trellis decoding",
    "bandwidth",
    "turbo code",
    "recurrence relation",
    "hyperparameter search",
    "interference temperature",
    "secret sharing",
    "linear regression",
    "round trip time",
    "special relativity",
    "non-orthogonal",
    "integer programming",
    "numerical methods",
    "protein folding",
    "gradient boosting",
    "belief revision",
    "SQL database",
    "finite volume method",
    "dot product",
    "beam search",
    "feature engineering",
    "authorization",
    "hessian matrix",
    "shared spectrum",
    "domain adaptation",
    "differential geometry",
    "shor's algorithm",
    "optimal transport",
    "transformer",
    "Lempel-Ziv",
    "block code",
    "filter bank",
    "devops",
    "emergence",
    "galileo",
    "mcmc methods",
    "gamma distribution",
    "formal methods",
    "stochastic differential equations",
    "topological graph theory",
    "network analysis",
    "human-robot interaction",
    "transformer model",
    "word2vec",
    "pose estimation",
    "Markov chain",
    "multipath",
    "expert systems",
    "file systems",
    "outlier detection",
    "continuous integration and continuous delivery (CI/CD)",
    "Monte Carlo tree search",
    "spatial index",
    "control theory",
    "transaction throughput",
    "spectral efficiency",
    "adiabatic quantum computing",
    "generative adversarial network",
    "covariance matrix",
    "hamming code",
    "multi-task learning",
    "data masking",
    "positive definite",
    "hyperparameter tuning",
    "data transformation",
    "complex networks",
    "user interface design",
    "chaos theory",
    "question answering",
    "statistical mechanics",
    "beamforming",
    "contextual embeddings",
    "data pipeline",
    "object detection",
    "root finding",
    "parallel programming",
    "golden ratio",
    "swarm intelligence",
    "rural area",
    "real-time systems",
    "time series analysis",
    "tokenomics",
    "explainable ai",
    "data lakes",
    "multiple access",
    "artificial life",
    "convolutional code",
    "doppler shift",
    "molecular dynamics",
    "systems neuroscience",
    "fastText",
    "unmarshalling",
    "model stacking",
    "strong consistency",
    "probabilistic reasoning",
    "macrocells",
    "identity-based encryption",
    "few-shot learning",
    "graph neural networks",
    "edge computing",
    "active learning",
    "semantic reasoning",
    "embedded systems",
    "oblivious transfer (OT)",
    "stochastic process",
    "password management",
    "digital signature",
    "secure hash",
    "latency",
    "model checking",
    "dynamic spectrum access",
    "symmetric encryption",
    "lossless compression",
    "proof of stake",
    "greedy decoding",
    "keccak",
    "inner product",
    "decentralized applications",
    "horizontal scaling",
    "analysis",
    "subcarrier spacing",
    "data lineage",
    "network topology",
    "randomness",
    "newSQL",
    "satellite handover",
    "system identification",
    "self-organization",
    "decryption",
    "3D modeling",
    "probability theory",
    "spectrum allocation",
    "sidechains",
    "knowledge graphs",
    "argon2",
    "knowledge representation and reasoning",
    "abstractive summarization",
    "cdma",
    "tree traversal",
    "inter-symbol interference",
    "meo",
    "distributed ledger technology",
    "integration testing",
    "key pair generation",
    "mimo",
    "cryptography",
    "sha-3",
    "quantum machine learning",
    "semantic web",
    "temporal difference learning",
    "tdma",
    "matrix factorization",
    "mean squared error",
    "user acceptance testing",
    "code injection",
    "moving average",
    "quantum key distribution (QKD)",
    "quantum entanglement",
    "social choice theory",
    "non-monotonic reasoning",
    "Raft consensus",
    "quantum algorithms",
    "mobile edge computing",
    "modulation scheme",
    "quantum communication",
    "abductive reasoning",
    "computational",
    "temporal logic",
    "predictive modeling",
    "lattice-based cryptography",
    "beamwidth",
    "gps",
    "vertical scaling",
    "reed-solomon code",
    "fermat's little theorem",
    "t-distribution",
    "bit error rate",
    "karush-kuhn-tucker conditions",
    "ontological engineering",
    "contrastive learning",
    "feature extraction",
    "extractive summarization",
    "clustering",
    "measure theory",
    "channel estimation",
    "convex hull",
    "quantum computing",
    "virtual reality",
    "correlation coefficient",
    "fuzz testing",
    "picocell",
    "outer product",
    "atomic swaps",
    "parallel processing",
    "differential privacy",
    "hash collision",
    "image segmentation",
    "rollups",
    "conditional probability",
    "antenna array",
    "cross-site scripting",
    "metadata management",
    "link budget",
    "event-driven architecture",
    "high energy physics",
    "CatBoost",
    "pilot signal",
    "data pipelines",
    "automated machine learning",
    "data analysis",
    "gRPC",
    "content negotiation",
    "k-anonymity",
    "malware analysis",
    "topological quantum computing",
    "resource allocation",
    "argumentation theory",
    "arithmetic coding",
    "schema evolution",
    "vblast",
    "normalization",
    "euclidean algorithm",
    "greatest common divisor",
    "secure multi-party computation",
    "decision tree",
    "game theory",
    "space complexity",
    "hierarchical clustering",
    "word embeddings",
    "calculus",
    "fading",
    "lime analysis",
    "intrusion detection",
    "principal component analysis",
    "self-supervised learning",
    "pbkdf2",
    "simulated annealing",
    "epistemic logic",
    "asymptotic analysis",
    "convolutional neural network",
    "free space loss",
    "blockchain interoperability",
    "condensed matter physics",
    "pseudonymization",
    "homomorphic encryption",
    "theorem proving",
    "quantum random number generators (QRNGs)",
    "genetic algorithms",
    "geo",
    "adaptive coding",
    "swarm robotics",
    "ue category",
    "zero-shot learning",
    "deserialization",
    "quantum biology",
    "coherence time",
    "zero-day exploit",
    "data governance",
    "modal logic",
    "statistics",
    "key management",
    "modeling",
    "linear algebra",
    "viterbi algorithm",
    "ontologies",
    "interpretable machine learning",
    "protocol buffer",
    "sharding",
    "serverless computing",
    "path loss",
    "software architecture",
    "program verification",
    "software-defined networking",
    "statistical modeling",
    "data lake",
    "particle swarm optimization",
    "data visualization",
    "computer animation",
    "latent variable model",
    "graph theory",
    "blending",
    "probabilistic programming",
    "risk assessment",
    "statistical inference",
    "computational physics",
    "hurst exponent",
    "agglomerative clustering",
    "causal inference",
    "message queue",
    "qpsk",
    "haptics",
    "state-action pair",
    "sentiment analysis",
    "stochastic calculus",
    "delay spread",
    "autopoiesis",
    "Bayesian inference",
    "maximum likelihood decoding",
    "dynamical systems",
    "proximal policy optimization",
    "policy gradients",
    "run-length encoding",
    "Kubernetes",
    "blockchain technology",
    "security testing",
    "complex analysis",
    "heterogeneous network",
    "area under curve",
    "attribute-based encryption",
    "cryptoeconomics",
    "simulation",
    "bi-directional model",
    "packet loss",
    "waveform",
    "security protocol",
    "lte",
    "orthogonal polarization",
    "finite element method",
    "dimensionality curse",
    "ultra-reliable low latency",
    "data compression",
    "cognitive science",
    "grid computing",
    "support vector classifier",
    "hyperplane",
    "LightGBM",
    "accessibility testing",
    "gram-schmidt process",
    "serverless architecture",
    "sequence-to-sequence",
    "voting systems",
    "combinations",
    "ontology matching",
    "animation",
    "leader election",
    "bayesian search",
    "kalman filtering",
    "feedback loop",
    "acid compliance",
    "proxy re-encryption",
    "convex optimization",
    "dimensionality reduction",
    "huffman coding",
    "bitmap index",
    "ELMo",
    "qam",
    "tabu search",
    "data partitioning",
    "blockchain",
    "utility theory",
    "optimal control",
    "multinomial distribution",
    "exponential distribution",
    "stablecoins",
    "constraint satisfaction",
    "metabolomics",
    "frequency reuse",
    "secure multi-party computation (MPC)",
    "spread spectrum",
    "differential equations",
    "rule-based systems",
    "synthetic data",
    "distributed computing",
    "semi-supervised learning",
    "earth station",
    "distributed systems",
    "trust region policy optimization",
    "duplexing",
    "big data",
    "zero-forcing",
    "prime number",
    "k-medoids",
    "multi-objective optimization",
    "asymmetric encryption",
    "serialization",
    "neural network",
    "secure multiparty computation",
    "pub-sub model",
    "direct sequence",
    "femtocell",
    "DBSCAN",
    "self-interference cancellation",
    "microservices",
    "data breach",
    "vector space",
    "quantum mechanics",
    "medical image analysis",
    "schrodinger equation",
    "cross-polarization interference",
    "grid search",
    "authentication",
    "regularization",
    "small-world networks",
    "ofdm",
    "wilson's theorem",
    "underlay network",
    "threshold cryptography",
    "call admission control",
    "manifold learning",
    "semantic similarity",
    "chinese remainder theorem",
    "cluster computing",
    "recurrent neural network",
    "quantum supremacy",
    "latent Dirichlet allocation",
    "counting principle",
    "general relativity",
    "quantum teleportation",
    "downlink",
    "quantum optics",
    "deep learning",
    "data replication",
    "prior probability",
    "web3",
    "linked list",
    "decision boundary",
    "bayesian inference",
    "kernel trick",
    "speech synthesis",
    "entropy",
    "cholesky decomposition",
    "fuzzy logic",
    "quantum cryptography",
    "frequency-domain",
    "root mean square",
    "key exchange",
    "positional encoding",
    "random graphs",
    "time-domain",
    "cloud architecture",
    "community detection",
    "singular value decomposition",
    "public key infrastructure",
    "audio processing",
    "gaussian processes",
    "computational fluid dynamics",
    "drug discovery",
    "diffie-hellman",
    "cr-ns",
    "encryption",
    "lossy compression",
    "astrophysics",
    "svd",
    "quantum error correction",
    "permutations",
    "B+ tree",
    "sequence modeling",
    "affinity propagation",
    "ldpc code",
    "symbolic computation",
    "complex adaptive systems",
    "adaptive control",
    "topological data analysis",
    "scientific computing",
    "thrift",
    "proteomics",
    "bpsk",
    "low earth orbit",
    "pigeonhole principle",
    "nr",
    "quantum annealing",
    "bagging",
    "handover",
    "robotics",
    "image recognition",
    "quantum",
    "ensemble method",
    "reaction kinetics",
    "elliptic curve cryptography",
    "classification",
    "eigenvectors",
    "glonass",
    "q-learning",
    "firewall",
    "meta-learning",
    "sha-256",
    "single carrier",
    "software-defined radio",
    "t-closeness",
    "linear inequality",
    "zero-knowledge proofs",
    "information visualization",
    "frame structure",
    "discrete logarithm problem",
    "pareto optimality",
    "evidence",
    "motion capture",
    "k-means clustering",
    "service-oriented architecture (SOA)",
    "verifiable computation",
    "proof of work",
    "part-of-speech tagging",
    "urban area",
    "continual learning",
    "cell search",
    "cybernetics",
    "quantum thermodynamics",
    "receiver operating characteristic",
    "backtracking",
    "error correction code",
    "cryptocurrencies",
    "logistic regression",
    "group theory",
    "synchronization",
    "hermitian matrix",
    "dependency parsing",
    "optimization",
    "public key",
    "random search",
    "penetration testing",
    "policy gradient",
    "trellis diagram",
    "Nash equilibrium",
    "quorum",
    "data warehouse",
    "cognitive robotics",
    "fuzzy systems",
    "fibonacci sequence",
    "birthday paradox",
    "content delivery network",
    "information retrieval",
    "threat analysis",
    "split learning",
    "consensus algorithm",
    "multivariate cryptography",
    "unsupervised learning",
    "data integrity",
    "random forest",
    "garbled circuits",
    "digital envelope",
    "convex set",
    "feature importance",
    "software engineering",
    "eigenvalues",
    "nonlinear optimization",
    "database indexing",
    "Docker",
    "explainable AI (XAI)",
    "ensemble learning",
    "seasonality",
    "system testing",
    "write-ahead log",
    "l-diversity",
    "real-time processing",
    "quantum simulation",
    "social network analysis",
    "independent component analysis",
    "geostationary orbit",
    "generating functions",
    "ETL (extract, transform, load)",
    "deontic logic",
    "hashing",
    "standardization",
    "spatial multiplexing",
    "decision theory",
    "robust control",
    "curriculum learning",
    "anomaly detection",
    "industrial internet of things (IIoT)",
    "quantum computer",
    "buffer overflow",
    "parallel computing",
    "chi-square distribution",
    "evolutionary strategies",
    "topology",
    "post-quantum cryptography",
    "bioinformatics",
    "graphQL",
    "elliptic curve point",
    "event-driven",
    "cache invalidation",
    "qubit",
    "attenuation",
    "lagrange multipliers",
    "metaverse",
    "maximum likelihood",
    "jpeg compression",
    "software development lifecycle",
    "genetic programming",
    "maclaurin series",
    "error vector magnitude",
    "layer-2 scaling solutions",
    "interference management",
    "memory management",
    "mmse equalizer",
    "cloud-native architecture",
    "B-tree",
    "satellite network",
    "natural language generation",
    "coherence bandwidth",
    "Fourier transform",
    "hash map",
    "cross product",
    "quantum materials",
    "sphere decoder",
    "crispr-cas9",
    "information theory",
    "quality of service",
    "usability testing",
    "fine-tuning",
    "small cell",
    "soft margin",
    "algebraic graph theory",
    "manifold theory",
    "bias-variance tradeoff",
    "streaming protocol",
    "abstract algebra",
    "program synthesis",
    "hash index",
    "recall",
    "scale-free networks",
    "deep q-network",
    "molecular orbital theory",
    "virtualized network functions",
    "natural language understanding",
    "long short-term memory",
    "satellite communications",
    "cosmology",
    "GloVe",
    "private set intersection (PSI)",
    "human-computer interaction",
    "text mining",
    "plasma",
    "3d reconstruction",
    "particle filtering",
    "adaptive systems",
    "convex function",
    "combinatorics",
    "synthetic biology",
    "data security",
    "orthogonalization",
    "personalized medicine",
    "stationarity",
    "data structures",
    "cyber-physical systems",
    "ACID properties",
    "uplink",
    "bayesian optimization",
    "data privacy",
    "superposition",
    "automated theorem proving",
    "containerization",
    "partial differential equations",
    "data anonymization",
    "self-attention",
    "time-division duplex",
    "sarsa",
    "Monte Carlo simulation",
    "code-based cryptography",
    "wireless sensor networks",
    "formal verification",
    "virtualization",
    "string theory",
    "device drivers",
    "cognitive radio",
    "marshalling",
    "signal-to-noise ratio",
    "secure aggregation",
    "quantum chemistry",
    "regression analysis",
    "artificial general intelligence",
    "autocorrelation",
    "bayesian networks",
    "static analysis",
    "kernel programming",
    "functional analysis",
    "masked language model",
    "binomial distribution",
    "Markov decision process",
    "CAP theorem",
    "spectral graph theory",
    "ransomware",
    "tensor calculus",
    "coreference resolution",
    "quantum communication networks",
    "f-distribution",
    "white space",
    "computer graphics",
    "lambda function",
    "software testing",
    "optimization theory",
    "approximation algorithm",
    "remote sensing",
    "reasoning systems",
    "taylor expansion",
    "private key",
    "machine translation",
    "text generation",
    "naive bayes classifier",
    "ELT (extract, load, transform)",
    "topic modeling",
    "K nearest neighbors",
    "computational linguistics",
    "performance testing",
    "loss function",
    "leo",
    "5g",
    "state channels",
    "event sourcing",
    "quantum gate",
    "adaptive modulation",
    "bio-inspired computing",
    "polarization",
    "sensor networks",
    "combinatorial optimization",
    "density functional theory",
    "least common multiple",
    "signal processing",
    "prescriptive modeling",
    "video encoding",
    "posterior probability",
    "design patterns",
    "PID controller",
    "unit testing",
    "nonlinear programming",
    "frequency domain analysis",
    "support vector machine",
    "fuzzy c-means",
    "actor-critic methods",
    "data science",
    "frequency hopping",
    "channel coding",
    "quadratic form",
    "shapley values",
    "brain-computer interfaces",
    "adversarial machine learning",
    "heisenberg uncertainty",
    "optimization problem",
    "gaussian distribution",
    "database sharding",
    "dynamic analysis",
    "poisson distribution",
    "NoSQL database",
    "transfer learning",
    "reinforcement learning",
    "pre-trained model",
    "user experience design",
    "internet of things (IoT)",
    "precision",
    "satellite footprint",
    "RESTful service",
    "systems biology",
    "code rate",
    "variational inference",
    "jacobian matrix",
    "f1 score",
    "actor-critic model",
    "non-fungible tokens (NFTs)",
    "Paxos algorithm",
    "decentralized finance (defi)",
    "identity verification",
    "control systems",
    "mixed reality",
    "evolutionary computation",
    "homomorphic secret sharing",
    "multi-agent systems",
    "eigen decomposition",
    "graph embedding",
    "overlay network",
    "wave-particle duality",
    "bioimaging",
    "federated learning",
    "preamble",
    "BERT",
    "knowledge representation",
    "isogeny-based cryptography",
    "fdma",
    "differential attack",
    "eventual consistency",
    "divide and conquer",
    "catalysis",
    "text summarization",
    "quantum metrology",
    "model interpretability",
    "actor model",
    "autoregressive model",
    "binomial theorem",
    "data mining",
]
